== Remove result duplicates

[options="step"]
`RETURN DISTINCT` returns only unique rows 

[source,cypher,options="step"]
----
MATCH (o:Org)-->(:Office)-->(:City)-->(c:Country)
WHERE o.name = "GraphIT"
RETURN DISTINCT c.name;
----

== Optional relationships

Pattern

++++
<figure class="graph-diagram">
  <ul class="graph-diagram-markup" data-internal-scale="1.54" data-external-scale="1">
    <li class="node" data-node-id="4" data-x="-1697.3037903549252" data-y="-31.244897959183675">
      <span class="caption">a</span>
    </li>
  </ul>
</figure>
++++

or
++++
<figure class="graph-diagram">
  <ul class="graph-diagram-markup" data-internal-scale="4.26" data-external-scale="1">
    <li class="node" data-node-id="4" data-x="-1697.3037903549252" data-y="-31.244897959183675">
      <span class="caption">a</span>
    </li>
    <li class="node" data-node-id="5" data-x="-1612.13025747108" data-y="-31.244897959183675">
      <span class="caption">b</span>
    </li>
    <li class="relationship" data-from="4" data-to="5">
      <span class="type">r</span>
    </li>
</ul>
</figure>
++++

[source,cypher,options="step"]
----
MATCH a
OPTIONAL MATCH (a)-[r]->(b)
RETURN a, b;
----

== Optional relationships

List organizations and their countries

[source,cypher,options="step"]
----
MATCH (o:Org)
OPTIONAL MATCH o-->(:Office)-->(:City)-->(c:Country)
RETURN DISTINCT o.name, c.name;
----

== Relationship attributes

[options="step"]
Relationships can have attributes as well

[source,cypher,options="step"]
----
MATCH (p:Person)<-[m:MEMBER]-(:Project)
WHERE p.name = "Charlene"
RETURN m.role;
----


== Paths

[source,cypher,options="step"]
----
MATCH p=(a:Person)<-[:EMPLOYEE]-(d)-[:EMPLOYEE]->(b:Person)
WHERE a.name = "Daniel"
RETURN p;
----

== Variable length paths

[source,cypher,options="step"]
----
MATCH p = (a)-[:REL*0..]->(b)
RETURN p;
----

[source,cypher,options="step"]
----
MATCH p = (a)-[:REL*1..3]->(b)
RETURN p;
----


== Result with alias

[options="step"]
`AS` sets name for result column

[source,cypher,options="step"]
----
MATCH (p)<-[:EMPLOYEE]-(d)
RETURN p.name as employee, 
  d.name as `department`;
----

[canvas-image="./img/aggregation-sw.jpg"]
== Aggregation

[role="canvas-caption", position="center"]
Aggregation

[role="img-ref"]
derivative of https://www.flickr.com/photos/zscheyge/49012397["Building Blocks"] by https://www.flickr.com/photos/zscheyge/[Holger Zscheyge] / http://creativecommons.org/licenses/by/2.0/[CC BY]

== Aggregation

[options="step"]
`count(*)` counts matching rows

[source,cypher,options="step"]
----
MATCH (p)<-[:EMPLOYEE]-(d)
RETURN d.name, count(*);
----

[options="step"]
`count(x)` counts non-NULL values in x

[source,cypher,options="step"]
----
MATCH (d:Dept)
OPTIONAL MATCH (p)<-[:EMPLOYEE]-(d)
RETURN d.name, count(p);
----


== Aggregation

[options="step"]
returns only departments with at least one member

[source,cypher,options="step"]
----
MATCH (p)<-[:EMPLOYEE]-(d)
RETURN d.name, count(*);
----


[options="step"]
returns all departments

[source,cypher,options="step"]
----
MATCH (d:Dept)
OPTIONAL MATCH (p)<-[:EMPLOYEE]-(d)
RETURN d.name, count(p);
----

== Collecting

[options="step"]
- `collect(x)` inserts all values into a list
- can be combined with `DISTINCT`

[source,cypher,options="step"]
----
MATCH (o:Org)-->(:Office)-->(:City)-->(c:Country)
RETURN o.name AS organization, 
  collect(DISTINCT c.name) as countries;
----

== Statistics

[options="step"]
- `min(x)` returns the lowest value
- `max(x)` returns the highest value
- `avg(x)` returns the average of a numeric value
- `sum(x)` returns the sum of all values
- and some more

== Sorting

[options="step"]
`ORDER BY expr [ASC|DESC]` sorts the results (by multiple properties)

[source,cypher,options="step"]
----
MATCH (city:City)-[:IS_IN]->(country:Country)
RETURN country.name, city.name
ORDER BY country.name, city.name;
----

== Limit and skip

[options="step"]
- `LIMIT x` returns only the first x entries
- `SKIP y` omits the first y entries

[source,cypher,options="step"]
----
MATCH (p:Person)
RETURN p.name
ORDER BY p.name
SKIP 3
LIMIT 5;
----

